//! `update-descriptions` — caption assets with a vision LLM, idempotently.
//!
//! Idempotency design (see README for the full story): each generated
//! description gets a trailing footer line `—generated by immich-cli/v2
//! sha=<12-char checksum prefix>`. On a future run we parse the footer
//! and decide:
//!   * empty description                          → caption
//!   * footer + sha matches asset.checksum + version matches → skip
//!   * footer with stale sha (file changed)       → re-caption
//!   * footer with older version                  → re-caption
//!   * non-empty description without our footer   → caption (overwrite
//!     the foreign value — in this library it's always camera/app noise
//!     like `cof`, `PixCake`, `Exif_JPEG_420`, never a real human caption)
//!
//! `--force` ignores even the "sha matches" check, useful when iterating
//! on the prompt without bumping the version constant.

use crate::client::{CaptionBackend, ImmichClient, InfoBackend, SearchBackend};
use crate::config::Config;
use crate::llm::{CaptionLlm, OpenAiClient};
use crate::models::{Asset, SearchRequest};
use crate::path_map;
use crate::places::{self, Admin2Lookup};
use anyhow::{anyhow, bail, Context, Result};
use clap::{Args, ValueEnum};
use std::collections::{BTreeMap, HashSet};
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Mutex;

/// Bumped whenever the prompt or model selection changes meaningfully;
/// older-version descriptions are treated as stale and re-captioned.
pub const CURRENT_VERSION: u32 = 2;

/// First N chars of the asset's base64 checksum embedded in the footer.
/// 12 base64 chars = 72 bits — plenty to detect file changes within a
/// library of millions of assets without collision risk.
pub const SHA_PREFIX_LEN: usize = 12;

/// Token budget for the vision call. mimo-v2.5 is a reasoning model that
/// burns tokens in `reasoning_content` before producing visible output;
/// 8K leaves room for ~3-4K reasoning plus a ~3000-char Chinese caption.
const MAX_COMPLETION_TOKENS: u32 = 8192;

#[derive(Args, Debug)]
pub struct UpdateDescriptionsArgs {
    /// If given, caption this single local NFS path. Otherwise scan the
    /// library subject to the filter flags below.
    pub path: Option<PathBuf>,

    /// Only consider assets whose `localDateTime` is at or after this
    /// timestamp. Same format as `search`: ISO 8601 or YYYY-MM-DD.
    #[arg(long, value_name = "DATE")]
    pub taken_after: Option<String>,

    /// Only consider assets whose `localDateTime` is at or before this.
    #[arg(long, value_name = "DATE")]
    pub taken_before: Option<String>,

    /// EXIF-derived geo filters; same exact-match semantics as `search`.
    #[arg(long)]
    pub city: Option<String>,
    #[arg(long)]
    pub state: Option<String>,
    #[arg(long)]
    pub country: Option<String>,

    /// Restrict to a single asset type.
    #[arg(long, value_enum)]
    pub r#type: Option<AssetTypeArg>,

    /// Maximum number of assets to process in this run (after the
    /// decision-tree filter, so it counts only assets we'd actually
    /// caption). `0` means no cap.
    #[arg(long, default_value_t = 0)]
    pub limit: u32,

    /// Number of concurrent vision-LLM workers. Each worker holds one
    /// asset; raise carefully — the upstream gateway may rate-limit.
    #[arg(long, default_value_t = 4)]
    pub parallel: u32,

    /// Print the decision for each asset but do NOT call the LLM and do
    /// NOT PUT anything back to Immich.
    #[arg(long)]
    pub dry_run: bool,

    /// Print the per-asset variable prompt facts sent to the vision LLM.
    /// Fixed prompt instructions and image bytes are omitted.
    #[arg(long)]
    pub verbose: bool,

    /// Ignore the "sha and version match → skip" rule. Useful when
    /// re-prompting the same library without bumping CURRENT_VERSION.
    #[arg(long)]
    pub force: bool,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum AssetTypeArg {
    Image,
    Video,
    Audio,
    Other,
}

impl AssetTypeArg {
    fn as_api_str(self) -> &'static str {
        match self {
            AssetTypeArg::Image => "IMAGE",
            AssetTypeArg::Video => "VIDEO",
            AssetTypeArg::Audio => "AUDIO",
            AssetTypeArg::Other => "OTHER",
        }
    }
}

// ---- footer marker -------------------------------------------------------

const FOOTER_PREFIX: &str = "—generated by immich-cli/v";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Footer {
    pub version: u32,
    pub sha_prefix: String,
}

/// Strip a trailing footer if one is present, returning the body and the
/// parsed footer separately. If no footer, returns the input unchanged
/// and `None`.
pub fn split_footer(description: &str) -> (&str, Option<Footer>) {
    // Footer is always on the last non-blank line.
    let trimmed = description.trim_end();
    let last_line_start = trimmed.rfind('\n').map(|i| i + 1).unwrap_or(0);
    let last_line = &trimmed[last_line_start..];
    let Some(rest) = last_line.strip_prefix(FOOTER_PREFIX) else {
        return (description, None);
    };
    let (version_str, after_version) = match rest.split_once(' ') {
        Some(p) => p,
        None => return (description, None),
    };
    let Ok(version) = version_str.parse::<u32>() else {
        return (description, None);
    };
    let sha_prefix = match after_version.strip_prefix("sha=") {
        Some(s) => s.to_string(),
        None => return (description, None),
    };

    // Body = everything before the footer line, trimmed of trailing
    // whitespace (we add `\n\n` ourselves on re-write).
    let body = trimmed[..last_line_start].trim_end();
    (
        body,
        Some(Footer {
            version,
            sha_prefix,
        }),
    )
}

/// Build the new description: body + blank line + footer.
pub fn assemble_with_footer(body: &str, checksum: &str) -> String {
    let body = body.trim_end();
    let prefix = sha_prefix(checksum);
    format!("{body}\n\n{FOOTER_PREFIX}{CURRENT_VERSION} sha={prefix}")
}

pub fn sha_prefix(checksum: &str) -> String {
    checksum.chars().take(SHA_PREFIX_LEN).collect()
}

/// What we want to do with one asset, given its current description and
/// the runtime flags. Pure function so the decision tree is unit-testable
/// independent of LLM / HTTP.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Decision {
    /// Description is empty or we control the footer — go (re-)caption.
    /// The reason is informational; tests assert on it.
    Caption(CaptionReason),
    /// Already up to date, leave alone.
    Skip(SkipReason),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CaptionReason {
    EmptyDescription,
    ChecksumChanged,
    VersionUpgraded,
    Forced,
    OverwroteForeign,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkipReason {
    UpToDate,
}

pub fn decide(description: Option<&str>, checksum: &str, force: bool) -> Decision {
    let desc = description.unwrap_or("").trim();
    if desc.is_empty() {
        return Decision::Caption(CaptionReason::EmptyDescription);
    }
    let (_, footer) = split_footer(desc);
    match footer {
        Some(f) => {
            // We own this description (we wrote it before).
            if force {
                Decision::Caption(CaptionReason::Forced)
            } else if f.sha_prefix != sha_prefix(checksum) {
                Decision::Caption(CaptionReason::ChecksumChanged)
            } else if f.version < CURRENT_VERSION {
                Decision::Caption(CaptionReason::VersionUpgraded)
            } else {
                Decision::Skip(SkipReason::UpToDate)
            }
        }
        // No footer = camera EXIF / app noise; always overwrite.
        None => Decision::Caption(CaptionReason::OverwroteForeign),
    }
}

// ---- prompt --------------------------------------------------------------

const CAPTION_SYSTEM_PROMPT: &str = "你是一位帮助用户为照片生成中文描述的助手。\
你的输出会作为搜索/检索系统的输入，因此需要尽可能全面、客观、可搜索。\
只输出可以直接写入照片 description 字段的正文，不要包含任何其他无意义内容。\
使用纯文本，只允许 Markdown 标题和列表用于区分层次结构，不要使用任何其他 Markdown 语法。";

const CAPTION_TASK_PROMPT: &str =
    "请尽可能详尽地分析这张图片，为一个纯文本的下游搜索/检索模型生成中文描述。\n\n\
请描述以下方面（按图片实际内容取舍，没有的可不写）：\n\
- 主体物体、人物（数量、姿态、衣着、动作、表情等可观察到的细节）\n\
- 场景、地理环境、室内或室外\n\
- 光线、色彩、氛围、季节/时间感\n\
- 布局与构图、前景与背景的关系\n\
- 任何能帮助识别具体地点、品牌、产品或场景的独特视觉线索\n\n\
规则：\n\
- 直接输出照片描述正文，不要写任务说明、开场白、总结或用途解释\n\
- 已知客观事实只作为锚定信息使用；可以用于写明时间、地点、已识别人物姓名/关系，但不能据此反推图中不可见的视觉细节\n\
- 不要因为日期推断节日、活动或季节装饰，除非图片里确实可见\n\
- 不要因为地点推断具体地标、景区、店铺或事件，除非图片里确实可见\n\
- 不要为未列出的陌生人编造姓名、亲属关系或身份；已列出的人物可以使用姓名和关系称谓\n\
- 严格区分\"观察到的事实\"和\"不确定的推断\"，不确定的部分请用\"看起来像\"、\"推测为\"等词标注\n\
- 不要做超出图像本身的猜测\n\
- 全文使用中文\n\
- 总长度不超过 1000 字";

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AssetContext {
    pub taken_at: Option<String>,
    pub location: Option<LocationContext>,
    pub people: Vec<PersonContext>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocationContext {
    pub country: Option<String>,
    pub state: Option<String>,
    pub admin2: Option<String>,
    pub city: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PersonContext {
    pub name: String,
    pub roles: Vec<String>,
}

impl AssetContext {
    fn prompt_facts(&self) -> String {
        let mut lines = Vec::new();
        if let Some(taken_at) = self.taken_at.as_deref() {
            lines.push(format!(
                "- 拍摄时间: {taken_at}（Immich localDateTime，按拍摄地本地时间理解）"
            ));
        }
        if let Some(location) = &self.location {
            lines.push(format!("- 地理位置: {}", location.prompt_value()));
        }
        if !self.people.is_empty() {
            let people = self
                .people
                .iter()
                .map(PersonContext::prompt_value)
                .collect::<Vec<_>>()
                .join("；");
            lines.push(format!("- 已识别人物: {people}"));
        }

        if lines.is_empty() {
            "- 无额外已知事实".to_string()
        } else {
            lines.join("\n")
        }
    }
}

impl LocationContext {
    fn prompt_value(&self) -> String {
        let mut parts = Vec::new();
        if let Some(country) = self.country.as_deref() {
            parts.push(format!("国家/地区: {country}"));
        }
        if let Some(state) = self.state.as_deref() {
            parts.push(format!("一级行政区: {state}"));
        }
        if let Some(admin2) = self.admin2.as_deref() {
            parts.push(format!("二级行政区: {admin2}"));
        }
        if let Some(city) = self.city.as_deref() {
            parts.push(format!("Immich city: {city}"));
        }
        parts.join("；")
    }
}

impl PersonContext {
    fn prompt_value(&self) -> String {
        if self.roles.is_empty() {
            self.name.clone()
        } else {
            format!("{}（{}）", self.name, self.roles.join("/"))
        }
    }
}

pub fn build_caption_user_prompt(context: &AssetContext) -> String {
    format!(
        "以下是 Immich 和用户配置提供的已知客观事实。\
请把它们作为锚定信息使用，但不要从这些事实编造图片里没有出现的内容。\n\n\
已知客观事实：\n{}\n\n{}",
        context.prompt_facts(),
        CAPTION_TASK_PROMPT
    )
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct CaptionPromptParts {
    variable_facts: String,
    user_prompt: String,
}

// ---- single-asset caption pipeline ---------------------------------------

fn cleaned(s: &Option<String>) -> Option<String> {
    s.as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .map(ToOwned::to_owned)
}

pub fn build_asset_context(
    asset: &Asset,
    full_asset: Option<&serde_json::Value>,
    people_map: &BTreeMap<String, Vec<String>>,
    admin2_lookup: &Admin2Lookup,
) -> AssetContext {
    AssetContext {
        taken_at: cleaned(&asset.local_date_time),
        location: build_location_context(asset, admin2_lookup),
        people: full_asset
            .map(|v| extract_configured_people(v, people_map))
            .unwrap_or_default(),
    }
}

fn build_location_context(asset: &Asset, admin2_lookup: &Admin2Lookup) -> Option<LocationContext> {
    let exif = asset.exif_info.as_ref()?;
    let country = cleaned(&exif.country);
    let state = cleaned(&exif.state);
    let city = cleaned(&exif.city);
    if country.is_none() && state.is_none() && city.is_none() {
        return None;
    }

    let admin2 = match (&country, &state, &city) {
        (Some(country), Some(state), Some(city)) => admin2_lookup
            .get(&(country.clone(), state.clone(), city.clone()))
            .cloned(),
        _ => None,
    };

    Some(LocationContext {
        country,
        state,
        admin2,
        city,
    })
}

fn extract_configured_people(
    full_asset: &serde_json::Value,
    people_map: &BTreeMap<String, Vec<String>>,
) -> Vec<PersonContext> {
    if people_map.is_empty() {
        return Vec::new();
    }

    let mut seen = HashSet::new();
    let mut people = Vec::new();
    let Some(items) = full_asset.get("people").and_then(|v| v.as_array()) else {
        return people;
    };

    for person in items {
        let Some(name) = person
            .get("name")
            .and_then(|v| v.as_str())
            .map(str::trim)
            .filter(|s| !s.is_empty())
        else {
            continue;
        };
        let Some(roles) = people_map.get(name) else {
            continue;
        };
        if !seen.insert(name.to_string()) {
            continue;
        }
        people.push(PersonContext {
            name: name.to_string(),
            roles: roles.clone(),
        });
    }

    people
}

fn build_caption_prompt_parts<I>(
    info_be: &I,
    asset: &Asset,
    people_map: &BTreeMap<String, Vec<String>>,
    admin2_lookup: &Admin2Lookup,
) -> Result<CaptionPromptParts>
where
    I: InfoBackend,
{
    let full_asset = if people_map.is_empty() {
        None
    } else {
        Some(
            info_be
                .get_asset(&asset.id)
                .with_context(|| format!("failed to fetch full asset detail for {}", asset.id))?,
        )
    };
    let context = build_asset_context(asset, full_asset.as_ref(), people_map, admin2_lookup);
    let variable_facts = context.prompt_facts();
    let user_prompt = build_caption_user_prompt(&context);
    Ok(CaptionPromptParts {
        variable_facts,
        user_prompt,
    })
}

fn caption_with_prompt_parts<C, V>(
    client: &C,
    llm: &V,
    asset: &Asset,
    prompt: &CaptionPromptParts,
) -> Result<String>
where
    C: CaptionBackend,
    V: CaptionLlm,
{
    let bytes = client.thumbnail(&asset.id)?;
    let body = llm.caption(
        CAPTION_SYSTEM_PROMPT,
        &prompt.user_prompt,
        &bytes,
        "image/jpeg",
        MAX_COMPLETION_TOKENS,
    )?;
    Ok(assemble_with_footer(body.trim(), &asset.checksum))
}

/// Produce a fresh description for one asset by fetching its full asset
/// detail (for configured people), fetching its thumbnail, and asking the
/// vision model. The footer is appended here.
pub fn caption_one<C, V>(
    client: &C,
    llm: &V,
    asset: &Asset,
    people_map: &BTreeMap<String, Vec<String>>,
    admin2_lookup: &Admin2Lookup,
) -> Result<String>
where
    C: CaptionBackend + InfoBackend,
    V: CaptionLlm,
{
    let prompt = build_caption_prompt_parts(client, asset, people_map, admin2_lookup)?;
    caption_with_prompt_parts(client, llm, asset, &prompt)
}

// ---- candidate enumeration -----------------------------------------------

fn enumerate_candidates<S: SearchBackend>(
    search: &S,
    args: &UpdateDescriptionsArgs,
) -> Result<Vec<Asset>> {
    let mut all = Vec::new();
    let mut page = 1u32;
    loop {
        let req = SearchRequest {
            taken_after: args.taken_after.clone(),
            taken_before: args.taken_before.clone(),
            city: args.city.clone(),
            state: args.state.clone(),
            country: args.country.clone(),
            asset_type: args.r#type.map(|t| t.as_api_str().to_string()),
            size: Some(1000),
            page: Some(page),
            with_exif: Some(true),
            ..Default::default()
        };
        let resp = search.search(&req)?;
        if resp.assets.items.is_empty() {
            break;
        }
        let has_more = resp.assets.next_page.as_ref().is_some_and(|v| !v.is_null());
        all.extend(resp.assets.items);
        if !has_more {
            break;
        }
        page += 1;
    }
    Ok(all)
}

fn resolve_single<S: SearchBackend>(
    cfg: &Config,
    search: &S,
    path: &std::path::Path,
) -> Result<Asset> {
    let local_abs = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .context("cannot resolve cwd")?
            .join(path)
    };
    let server_path = path_map::reverse_translate(&local_abs.to_string_lossy(), &cfg.path_map)
        .ok_or_else(|| {
            anyhow!(
                "no path mapping matches {} — add a [[path_map]] entry",
                local_abs.display()
            )
        })?;
    let filename = std::path::Path::new(&server_path)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .ok_or_else(|| anyhow!("could not extract filename from `{server_path}`"))?;
    let req = SearchRequest {
        original_file_name: Some(filename.clone()),
        size: Some(250),
        with_exif: Some(true),
        ..Default::default()
    };
    let resp = search.search(&req)?;
    let mut matches: Vec<Asset> = resp
        .assets
        .items
        .into_iter()
        .filter(|a| a.original_path == server_path)
        .collect();
    match matches.len() {
        0 => bail!(
            "no Immich asset has originalPath `{server_path}` \
             (filename `{filename}` was not found)"
        ),
        1 => Ok(matches.pop().unwrap()),
        n => bail!(
            "{n} Immich assets share originalPath `{server_path}` \
             — should never happen"
        ),
    }
}

// ---- orchestration -------------------------------------------------------

pub fn run(cfg: &Config, args: UpdateDescriptionsArgs) -> Result<()> {
    let llm_cfg = cfg.llm.as_ref().ok_or_else(|| {
        anyhow!(
            "update-descriptions requires an [llm] section in config.toml \
             with vision_model set"
        )
    })?;
    if llm_cfg.vision_model.as_deref().unwrap_or("").is_empty() {
        bail!(
            "update-descriptions requires config.llm.vision_model — set it to a \
             vision-capable model (e.g. \"mimo-v2.5\")"
        );
    }
    let client = ImmichClient::new(cfg)?;
    let llm = OpenAiClient::new(llm_cfg)?;
    let mut stderr = std::io::stderr();
    let admin2_lookup = load_default_admin2_lookup(&mut stderr);
    run_with_admin2(
        cfg,
        &client,
        &client,
        &llm,
        args,
        &admin2_lookup,
        &mut stderr,
    )
}

fn load_default_admin2_lookup<W: std::io::Write>(log: &mut W) -> Admin2Lookup {
    let Some(path) = places::default_admin2_lookup_path() else {
        return Admin2Lookup::new();
    };
    match places::load_admin2_lookup(&path) {
        Ok(lookup) => lookup,
        Err(e) => {
            writeln!(
                log,
                "warn: could not load {} for caption location context: {e:#}",
                path.display()
            )
            .ok();
            Admin2Lookup::new()
        }
    }
}

/// Test/library entry point: decouples the runtime from concrete client
/// and LLM types. Logging goes to `log` so tests can capture it.
pub fn run_with<S, C, V, W>(
    cfg: &Config,
    search: &S,
    caption_be: &C,
    llm: &V,
    args: UpdateDescriptionsArgs,
    log: &mut W,
) -> Result<()>
where
    S: SearchBackend + Sync,
    C: CaptionBackend + InfoBackend + Sync,
    V: CaptionLlm + Sync,
    W: std::io::Write + Send,
{
    let admin2_lookup = Admin2Lookup::new();
    run_with_admin2(cfg, search, caption_be, llm, args, &admin2_lookup, log)
}

fn run_with_admin2<S, C, V, W>(
    cfg: &Config,
    search: &S,
    caption_be: &C,
    llm: &V,
    args: UpdateDescriptionsArgs,
    admin2_lookup: &Admin2Lookup,
    log: &mut W,
) -> Result<()>
where
    S: SearchBackend + Sync,
    C: CaptionBackend + InfoBackend + Sync,
    V: CaptionLlm + Sync,
    W: std::io::Write + Send,
{
    if args.parallel == 0 {
        bail!("--parallel must be > 0");
    }

    let candidates = if let Some(p) = &args.path {
        vec![resolve_single(cfg, search, p)?]
    } else {
        writeln!(log, "scanning library ...").ok();
        enumerate_candidates(search, &args)?
    };
    writeln!(log, "{} asset(s) match filter", candidates.len()).ok();

    // Decide per asset BEFORE we burn LLM tokens. This lets dry-run be
    // a true preview, and lets --limit cap captions (not enumeration).
    let planned: Vec<(Asset, Decision)> = candidates
        .into_iter()
        .map(|a| {
            let desc = a.exif_info.as_ref().and_then(|e| e.description.as_deref());
            let dec = decide(desc, &a.checksum, args.force);
            (a, dec)
        })
        .collect();

    let work: Vec<&(Asset, Decision)> = planned
        .iter()
        .filter(|(_, d)| matches!(d, Decision::Caption(_)))
        .take(if args.limit == 0 {
            usize::MAX
        } else {
            args.limit as usize
        })
        .collect();

    let skipped_up_to_date = planned
        .iter()
        .filter(|(_, d)| matches!(d, Decision::Skip(SkipReason::UpToDate)))
        .count();
    writeln!(
        log,
        "{} up to date, {} to caption",
        skipped_up_to_date,
        work.len()
    )
    .ok();

    if args.dry_run {
        for (asset, dec) in &work {
            if let Decision::Caption(r) = dec {
                writeln!(
                    log,
                    "DRY-RUN caption ({:?}): {} {}",
                    r, asset.id, asset.original_path
                )
                .ok();
                if args.verbose {
                    match build_caption_prompt_parts(caption_be, asset, &cfg.people, admin2_lookup)
                    {
                        Ok(prompt) => write_verbose_prompt_facts(log, asset, *r, &prompt).ok(),
                        Err(e) => writeln!(
                            log,
                            "DRY-RUN prompt unavailable: {} {} — {e:#}",
                            asset.id, asset.original_path
                        )
                        .ok(),
                    };
                }
            }
        }
        return Ok(());
    }

    if work.is_empty() {
        return Ok(());
    }

    process_in_parallel(
        caption_be,
        llm,
        &work,
        PromptDeps {
            people_map: &cfg.people,
            admin2_lookup,
        },
        args.parallel as usize,
        args.verbose,
        log,
    )
}

fn write_verbose_prompt_facts<W: std::io::Write>(
    log: &mut W,
    asset: &Asset,
    reason: CaptionReason,
    prompt: &CaptionPromptParts,
) -> std::io::Result<()> {
    writeln!(
        log,
        "[verbose] update-descriptions: prompt facts ({:?}): {} {}",
        reason, asset.id, asset.original_path
    )?;
    writeln!(
        log,
        "[verbose] update-descriptions: ---- variable prompt begin ----"
    )?;
    writeln!(log, "已知客观事实：")?;
    writeln!(log, "{}", prompt.variable_facts)?;
    writeln!(
        log,
        "[verbose] update-descriptions: ---- variable prompt end ----"
    )
}

/// References to the two inputs every prompt build needs: the user's
/// configured people map (for identity context) and the admin2 lookup
/// (for second-level administrative region enrichment). Bundled because
/// they're always passed together and would otherwise push the
/// orchestrator over clippy's argument-count threshold.
#[derive(Copy, Clone)]
struct PromptDeps<'a> {
    people_map: &'a BTreeMap<String, Vec<String>>,
    admin2_lookup: &'a Admin2Lookup,
}

/// Run vision + PUT for each item in parallel. Errors on individual
/// assets are logged but do not abort the whole run.
fn process_in_parallel<C, V, W>(
    caption_be: &C,
    llm: &V,
    work: &[&(Asset, Decision)],
    deps: PromptDeps<'_>,
    parallel: usize,
    verbose: bool,
    log: &mut W,
) -> Result<()>
where
    C: CaptionBackend + InfoBackend + Sync,
    V: CaptionLlm + Sync,
    W: std::io::Write + Send,
{
    let next = AtomicUsize::new(0);
    let succeeded = AtomicUsize::new(0);
    let failed = AtomicUsize::new(0);
    let log_lock = Mutex::new(log);

    std::thread::scope(|scope| {
        for _ in 0..parallel.min(work.len()) {
            scope.spawn(|| loop {
                let i = next.fetch_add(1, Ordering::SeqCst);
                if i >= work.len() {
                    break;
                }
                let (asset, decision) = work[i];
                let reason = match decision {
                    Decision::Caption(r) => *r,
                    Decision::Skip(_) => unreachable!("filtered above"),
                };
                let res = build_caption_prompt_parts(
                    caption_be,
                    asset,
                    deps.people_map,
                    deps.admin2_lookup,
                )
                    .and_then(|prompt| {
                        if verbose {
                            let mut log = log_lock.lock().unwrap();
                            write_verbose_prompt_facts(&mut *log, asset, reason, &prompt).ok();
                        }
                        caption_with_prompt_parts(caption_be, llm, asset, &prompt)
                    })
                    .and_then(|new_desc| caption_be.update_description(&asset.id, &new_desc));
                let mut log = log_lock.lock().unwrap();
                match res {
                    Ok(()) => {
                        succeeded.fetch_add(1, Ordering::SeqCst);
                        writeln!(
                            *log,
                            "ok ({:?}) [{}/{}]: {} {}",
                            reason,
                            i + 1,
                            work.len(),
                            asset.id,
                            asset.original_path
                        )
                        .ok();
                    }
                    Err(e) => {
                        failed.fetch_add(1, Ordering::SeqCst);
                        writeln!(
                            *log,
                            "FAIL [{}/{}]: {} {} — {e:#}",
                            i + 1,
                            work.len(),
                            asset.id,
                            asset.original_path
                        )
                        .ok();
                    }
                }
            });
        }
    });

    let log = log_lock.into_inner().unwrap();
    writeln!(
        log,
        "done: {} captioned, {} failed",
        succeeded.into_inner(),
        failed.into_inner()
    )
    .ok();
    Ok(())
}

// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::PathMapEntry;
    use crate::models::{AssetsBucket, ExifInfo, SearchResponse};
    use std::cell::RefCell;
    use std::sync::Mutex;

    fn asset_with(id: &str, path: &str, checksum: &str, description: Option<&str>) -> Asset {
        Asset {
            id: id.into(),
            original_path: path.into(),
            original_file_name: path.rsplit('/').next().unwrap_or(path).into(),
            asset_type: "IMAGE".into(),
            file_created_at: None,
            local_date_time: None,
            checksum: checksum.into(),
            exif_info: Some(ExifInfo {
                description: description.map(String::from),
                ..Default::default()
            }),
        }
    }

    fn cfg() -> Config {
        Config {
            server_url: "http://x".into(),
            api_key: "k".into(),
            path_map: vec![PathMapEntry {
                server: "/mnt/qnap".into(),
                local: "/home/u/Photos".into(),
            }],
            timeout_secs: 60,
            llm: None,
            people: std::collections::BTreeMap::new(),
        }
    }

    // ---- footer parsing ----

    #[test]
    fn split_footer_extracts_version_and_sha() {
        let s = "正文内容\n\n—generated by immich-cli/v1 sha=abc123def456";
        let (body, footer) = split_footer(s);
        assert_eq!(body, "正文内容");
        assert_eq!(
            footer,
            Some(Footer {
                version: 1,
                sha_prefix: "abc123def456".into()
            })
        );
    }

    #[test]
    fn split_footer_handles_v2_and_longer_sha() {
        let s = "x\n\n—generated by immich-cli/v42 sha=ZZZZZZZZZZZZZ";
        let (_, footer) = split_footer(s);
        let f = footer.unwrap();
        assert_eq!(f.version, 42);
        assert_eq!(f.sha_prefix, "ZZZZZZZZZZZZZ");
    }

    #[test]
    fn split_footer_returns_none_when_absent() {
        let s = "a human-written caption with no marker";
        let (body, footer) = split_footer(s);
        assert_eq!(body, s);
        assert!(footer.is_none());
    }

    #[test]
    fn split_footer_returns_none_on_malformed() {
        for s in [
            "x\n—generated by immich-cli/vONE sha=abc",
            "x\n—generated by immich-cli/v1",
            "x\n—generated by immich-cli/v1 sh=abc",
        ] {
            let (body, footer) = split_footer(s);
            assert_eq!(body, s, "input: {s}");
            assert!(footer.is_none(), "input: {s}");
        }
    }

    #[test]
    fn assemble_round_trips() {
        let body = "这是描述正文";
        let combined = assemble_with_footer(body, "kL2A3+Icry1aqhydhTrFlw2LZ/U=");
        let (got_body, footer) = split_footer(&combined);
        assert_eq!(got_body, body);
        let f = footer.unwrap();
        assert_eq!(f.version, CURRENT_VERSION);
        assert_eq!(f.sha_prefix, "kL2A3+Icry1a");
    }

    // ---- decide() ----

    #[test]
    fn decide_caption_when_description_is_none_or_empty() {
        let d1 = decide(None, "abc", false);
        let d2 = decide(Some(""), "abc", false);
        let d3 = decide(Some("   "), "abc", false);
        for d in [d1, d2, d3] {
            assert_eq!(d, Decision::Caption(CaptionReason::EmptyDescription));
        }
    }

    #[test]
    fn decide_skip_when_up_to_date() {
        let footer = assemble_with_footer("正文", "abcdef123456xyz");
        let d = decide(Some(&footer), "abcdef123456xyz", false);
        assert_eq!(d, Decision::Skip(SkipReason::UpToDate));
    }

    #[test]
    fn decide_recaption_when_sha_changes() {
        let footer = assemble_with_footer("正文", "OLD_CHECKSUM_____");
        let d = decide(Some(&footer), "NEW_CHECKSUM_____", false);
        assert_eq!(d, Decision::Caption(CaptionReason::ChecksumChanged));
    }

    #[test]
    fn decide_recaption_when_version_older() {
        let s = format!(
            "正文\n\n—generated by immich-cli/v0 sha={}",
            sha_prefix("abc")
        );
        let d = decide(Some(&s), "abc", false);
        assert_eq!(d, Decision::Caption(CaptionReason::VersionUpgraded));
    }

    #[test]
    fn decide_caption_when_foreign_description() {
        // No footer = camera noise; always overwrite.
        for s in ["cof", "PixCake", "Exif_JPEG_420", "a human-written caption"] {
            let d = decide(Some(s), "abc", false);
            assert_eq!(
                d,
                Decision::Caption(CaptionReason::OverwroteForeign),
                "input: {s}"
            );
        }
    }

    #[test]
    fn decide_force_overrides_uptodate() {
        let footer = assemble_with_footer("正文", "abcdef123456xyz");
        let d = decide(Some(&footer), "abcdef123456xyz", false);
        assert_eq!(d, Decision::Skip(SkipReason::UpToDate));
        let forced = decide(Some(&footer), "abcdef123456xyz", true);
        assert_eq!(forced, Decision::Caption(CaptionReason::Forced));
    }

    // ---- end-to-end via run_with ----

    struct FakeSearch {
        responses: RefCell<Vec<SearchResponse>>,
        calls: RefCell<Vec<SearchRequest>>,
    }
    impl FakeSearch {
        fn new(responses: Vec<SearchResponse>) -> Self {
            Self {
                responses: RefCell::new(responses),
                calls: RefCell::new(vec![]),
            }
        }
    }
    impl SearchBackend for FakeSearch {
        fn search(&self, req: &SearchRequest) -> Result<SearchResponse> {
            self.calls.borrow_mut().push(req.clone());
            Ok(self.responses.borrow_mut().remove(0))
        }
    }
    // SearchBackend isn't naturally Sync (RefCell); wrap.
    unsafe impl Sync for FakeSearch {}

    struct FakeCaption {
        thumbnails: Mutex<std::collections::HashMap<String, Vec<u8>>>,
        asset_details: Mutex<std::collections::HashMap<String, serde_json::Value>>,
        asset_detail_failures: Mutex<HashSet<String>>,
        updates: Mutex<Vec<(String, String)>>,
    }
    impl FakeCaption {
        fn new() -> Self {
            Self {
                thumbnails: Mutex::new(std::collections::HashMap::new()),
                asset_details: Mutex::new(std::collections::HashMap::new()),
                asset_detail_failures: Mutex::new(HashSet::new()),
                updates: Mutex::new(vec![]),
            }
        }
    }
    impl CaptionBackend for FakeCaption {
        fn thumbnail(&self, id: &str) -> Result<Vec<u8>> {
            Ok(self
                .thumbnails
                .lock()
                .unwrap()
                .get(id)
                .cloned()
                .unwrap_or_else(|| vec![0u8; 32]))
        }
        fn update_description(&self, id: &str, description: &str) -> Result<()> {
            self.updates
                .lock()
                .unwrap()
                .push((id.into(), description.into()));
            Ok(())
        }
    }
    impl InfoBackend for FakeCaption {
        fn get_asset(&self, id: &str) -> Result<serde_json::Value> {
            if self.asset_detail_failures.lock().unwrap().contains(id) {
                bail!("configured asset detail failure for {id}");
            }
            Ok(self
                .asset_details
                .lock()
                .unwrap()
                .get(id)
                .cloned()
                .unwrap_or_else(|| serde_json::json!({ "people": [] })))
        }

        fn albums_for_asset(&self, _id: &str) -> Result<serde_json::Value> {
            Ok(serde_json::json!([]))
        }

        fn ocr_for_asset(&self, _id: &str) -> Result<serde_json::Value> {
            Ok(serde_json::json!([]))
        }
    }

    struct FakeVision {
        reply: String,
    }
    impl CaptionLlm for FakeVision {
        fn caption(
            &self,
            _system_prompt: &str,
            _user_prompt: &str,
            _image_bytes: &[u8],
            _mime: &str,
            _max_tokens: u32,
        ) -> Result<String> {
            Ok(self.reply.clone())
        }
    }

    fn bucket(items: Vec<Asset>) -> SearchResponse {
        SearchResponse {
            assets: AssetsBucket {
                total: items.len() as u32,
                count: items.len() as u32,
                items,
                next_page: None,
            },
        }
    }

    fn args() -> UpdateDescriptionsArgs {
        UpdateDescriptionsArgs {
            path: None,
            taken_after: None,
            taken_before: None,
            city: None,
            state: None,
            country: None,
            r#type: None,
            limit: 0,
            parallel: 2,
            dry_run: false,
            verbose: false,
            force: false,
        }
    }

    #[test]
    fn build_asset_context_includes_time_location_admin2_and_configured_people() {
        let mut asset = asset_with("a", "/mnt/qnap/a.jpg", "cs-a", None);
        asset.local_date_time = Some("2024-03-12T17:08:42.000".into());
        let exif = asset.exif_info.as_mut().unwrap();
        exif.country = Some("People's Republic of China".into());
        exif.state = Some("Hainan".into());
        exif.city = Some("Haitangwan".into());

        let full_asset = serde_json::json!({
            "people": [
                { "name": "测试人物甲" },
                { "name": "未配置测试人物" },
                { "name": "测试人物乙" },
                { "name": "测试人物甲" }
            ]
        });
        let mut people = std::collections::BTreeMap::new();
        people.insert("测试人物甲".into(), vec!["妻子".into(), "妈妈".into()]);
        people.insert("测试人物乙".into(), vec!["女儿".into(), "孩子".into()]);

        let mut lookup = Admin2Lookup::new();
        lookup.insert(
            (
                "People's Republic of China".into(),
                "Hainan".into(),
                "Haitangwan".into(),
            ),
            "三亚市".into(),
        );

        let context = build_asset_context(&asset, Some(&full_asset), &people, &lookup);
        assert_eq!(context.taken_at.as_deref(), Some("2024-03-12T17:08:42.000"));
        assert_eq!(
            context.location.as_ref().and_then(|l| l.admin2.as_deref()),
            Some("三亚市")
        );
        assert_eq!(
            context.people,
            vec![
                PersonContext {
                    name: "测试人物甲".into(),
                    roles: vec!["妻子".into(), "妈妈".into()],
                },
                PersonContext {
                    name: "测试人物乙".into(),
                    roles: vec!["女儿".into(), "孩子".into()],
                },
            ]
        );

        let prompt = build_caption_user_prompt(&context);
        assert!(prompt.contains("2024-03-12T17:08:42.000"), "{prompt}");
        assert!(prompt.contains("二级行政区: 三亚市"), "{prompt}");
        assert!(prompt.contains("测试人物甲（妻子/妈妈）"), "{prompt}");
        assert!(prompt.contains("测试人物乙（女儿/孩子）"), "{prompt}");
        assert!(!prompt.contains("未配置测试人物"), "{prompt}");
    }

    #[test]
    fn run_with_captions_empty_and_foreign_descriptions() {
        let search = FakeSearch::new(vec![bucket(vec![
            asset_with("a", "/mnt/qnap/a.jpg", "cs-a-xxxxx", None),
            asset_with("b", "/mnt/qnap/b.jpg", "cs-b-xxxxx", Some("cof")),
            asset_with(
                "c",
                "/mnt/qnap/c.jpg",
                "cs-c-xxxxx",
                Some(&assemble_with_footer("旧描述", "cs-c-xxxxx")),
            ),
        ])]);
        let caption = FakeCaption::new();
        let vision = FakeVision {
            reply: "新描述".into(),
        };
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, args(), &mut log).unwrap();

        let mut updates = caption.updates.lock().unwrap().clone();
        updates.sort_by(|a, b| a.0.cmp(&b.0));
        // 'a' (empty) and 'b' (foreign noise) both captioned; 'c' up-to-date.
        assert_eq!(updates.len(), 2, "got: {updates:?}");
        assert_eq!(updates[0].0, "a");
        assert_eq!(updates[1].0, "b");
        for u in &updates {
            assert!(u.1.contains("新描述"));
            assert!(u.1.contains("—generated by immich-cli/v"));
        }

        let log_s = String::from_utf8(log).unwrap();
        assert!(log_s.contains("up to date"), "{log_s}");
    }

    #[test]
    fn run_with_dry_run_does_not_call_llm_or_update() {
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "a",
            "/mnt/qnap/a.jpg",
            "cs-a-xxxxx",
            None,
        )])]);
        let caption = FakeCaption::new();
        let vision = FakeVision { reply: "X".into() };
        let mut a = args();
        a.dry_run = true;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        assert!(caption.updates.lock().unwrap().is_empty());
        let log_s = String::from_utf8(log).unwrap();
        assert!(log_s.contains("DRY-RUN"));
    }

    #[test]
    fn run_with_verbose_logs_only_variable_prompt_facts() {
        let mut asset = asset_with("a", "/mnt/qnap/a.jpg", "cs-a-xxxxx", None);
        asset.local_date_time = Some("2024-03-12T17:08:42.000".into());
        let search = FakeSearch::new(vec![bucket(vec![asset])]);
        let caption = FakeCaption::new();
        caption
            .thumbnails
            .lock()
            .unwrap()
            .insert("a".into(), b"aW1hZ2UtYnl0ZXM=".to_vec());
        let vision = FakeVision {
            reply: "新描述".into(),
        };
        let mut a = args();
        a.parallel = 1;
        a.verbose = true;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();

        let log_s = String::from_utf8(log).unwrap();
        assert!(
            log_s.contains("[verbose] update-descriptions: ---- variable prompt begin ----"),
            "{log_s}"
        );
        assert!(log_s.contains("已知客观事实："), "{log_s}");
        assert!(
            log_s.contains("拍摄时间: 2024-03-12T17:08:42.000"),
            "{log_s}"
        );
        assert!(!log_s.contains("请尽可能详尽地分析这张图片"), "{log_s}");
        assert!(!log_s.contains("aW1hZ2UtYnl0ZXM="), "{log_s}");
    }

    #[test]
    fn run_with_force_replaces_up_to_date() {
        let existing = assemble_with_footer("旧的", "cs-a");
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "a",
            "/mnt/qnap/a.jpg",
            "cs-a",
            Some(&existing),
        )])]);
        let caption = FakeCaption::new();
        let vision = FakeVision {
            reply: "新的".into(),
        };
        let mut a = args();
        a.force = true;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        let updates = caption.updates.lock().unwrap();
        assert_eq!(updates.len(), 1);
        assert!(updates[0].1.contains("新的"));
    }

    #[test]
    fn run_with_limit_caps_captions_not_enumeration() {
        // 3 empty assets; --limit 2 means only the first two get LLM'd
        let search = FakeSearch::new(vec![bucket(vec![
            asset_with("a", "/mnt/qnap/a.jpg", "cs-a", None),
            asset_with("b", "/mnt/qnap/b.jpg", "cs-b", None),
            asset_with("c", "/mnt/qnap/c.jpg", "cs-c", None),
        ])]);
        let caption = FakeCaption::new();
        let vision = FakeVision { reply: "x".into() };
        let mut a = args();
        a.limit = 2;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        assert_eq!(caption.updates.lock().unwrap().len(), 2);
    }

    #[test]
    fn run_with_asset_detail_failure_logs_error_and_skips_that_asset() {
        let search = FakeSearch::new(vec![bucket(vec![
            asset_with("good", "/mnt/qnap/good.jpg", "cs-good", None),
            asset_with("bad", "/mnt/qnap/bad.jpg", "cs-bad", None),
        ])]);
        let caption = FakeCaption::new();
        caption
            .asset_detail_failures
            .lock()
            .unwrap()
            .insert("bad".into());
        let vision = FakeVision {
            reply: "新描述".into(),
        };
        let mut cfg = cfg();
        cfg.people
            .insert("测试人物乙".into(), vec!["女儿".into(), "孩子".into()]);

        let mut log = Vec::new();
        run_with(&cfg, &search, &caption, &vision, args(), &mut log).unwrap();

        let updates = caption.updates.lock().unwrap();
        assert_eq!(updates.len(), 1);
        assert_eq!(updates[0].0, "good");

        let log_s = String::from_utf8(log).unwrap();
        assert!(log_s.contains("FAIL"), "{log_s}");
        assert!(
            log_s.contains("failed to fetch full asset detail for bad"),
            "{log_s}"
        );
        assert!(log_s.contains("done: 1 captioned, 1 failed"), "{log_s}");
    }

    #[test]
    fn caption_one_appends_footer() {
        let caption = FakeCaption::new();
        let llm = FakeVision {
            reply: "正文".into(),
        };
        let asset = asset_with("asset-id", "/mnt/qnap/a.jpg", "checksum-xyz-aaa", None);
        let got = caption_one(
            &caption,
            &llm,
            &asset,
            &std::collections::BTreeMap::new(),
            &Admin2Lookup::new(),
        )
        .unwrap();
        let (body, footer) = split_footer(&got);
        assert_eq!(body, "正文");
        let f = footer.unwrap();
        assert_eq!(f.version, CURRENT_VERSION);
        assert_eq!(f.sha_prefix, "checksum-xyz");
    }

    // ---- single-asset path resolution ----

    #[test]
    fn resolve_single_uses_reverse_path_mapping() {
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "the-id",
            "/mnt/qnap/Family/x.jpg",
            "cs",
            None,
        )])]);
        let got = resolve_single(
            &cfg(),
            &search,
            std::path::Path::new("/home/u/Photos/Family/x.jpg"),
        )
        .unwrap();
        assert_eq!(got.id, "the-id");
    }

    #[test]
    fn resolve_single_errors_when_no_mapping() {
        let search = FakeSearch::new(vec![]);
        let err = resolve_single(&cfg(), &search, std::path::Path::new("/elsewhere/x.jpg"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("no path mapping"));
    }
}
