//! `update-descriptions` — caption assets with a vision LLM, idempotently.
//!
//! Idempotency design (see README for the full story): each generated
//! description gets a trailing footer line `—generated by immich-cli/v1
//! sha=<12-char checksum prefix>`. On a future run we parse the footer
//! and decide:
//!   * empty description                          → caption
//!   * footer + sha matches asset.checksum + version matches → skip
//!   * footer with stale sha (file changed)       → re-caption
//!   * footer with older version                  → re-caption
//!   * non-empty description without our footer   → caption (overwrite
//!     the foreign value — in this library it's always camera/app noise
//!     like `cof`, `PixCake`, `Exif_JPEG_420`, never a real human caption)
//!
//! `--force` ignores even the "sha matches" check, useful when iterating
//! on the prompt without bumping the version constant.

use crate::client::{CaptionBackend, ImmichClient, SearchBackend};
use crate::config::Config;
use crate::llm::{CaptionLlm, OpenAiClient};
use crate::models::{Asset, SearchRequest};
use crate::path_map;
use anyhow::{anyhow, bail, Context, Result};
use clap::{Args, ValueEnum};
use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Mutex;

/// Bumped whenever the prompt or model selection changes meaningfully;
/// older-version descriptions are treated as stale and re-captioned.
pub const CURRENT_VERSION: u32 = 1;

/// First N chars of the asset's base64 checksum embedded in the footer.
/// 12 base64 chars = 72 bits — plenty to detect file changes within a
/// library of millions of assets without collision risk.
pub const SHA_PREFIX_LEN: usize = 12;

/// Token budget for the vision call. mimo-v2.5 is a reasoning model that
/// burns tokens in `reasoning_content` before producing visible output;
/// 8K leaves room for ~3-4K reasoning plus a ~3000-char Chinese caption.
const MAX_COMPLETION_TOKENS: u32 = 8192;

#[derive(Args, Debug)]
pub struct UpdateDescriptionsArgs {
    /// If given, caption this single local NFS path. Otherwise scan the
    /// library subject to the filter flags below.
    pub path: Option<PathBuf>,

    /// Only consider assets whose `localDateTime` is at or after this
    /// timestamp. Same format as `search`: ISO 8601 or YYYY-MM-DD.
    #[arg(long, value_name = "DATE")]
    pub taken_after: Option<String>,

    /// Only consider assets whose `localDateTime` is at or before this.
    #[arg(long, value_name = "DATE")]
    pub taken_before: Option<String>,

    /// EXIF-derived geo filters; same exact-match semantics as `search`.
    #[arg(long)]
    pub city: Option<String>,
    #[arg(long)]
    pub state: Option<String>,
    #[arg(long)]
    pub country: Option<String>,

    /// Restrict to a single asset type.
    #[arg(long, value_enum)]
    pub r#type: Option<AssetTypeArg>,

    /// Maximum number of assets to process in this run (after the
    /// decision-tree filter, so it counts only assets we'd actually
    /// caption). `0` means no cap.
    #[arg(long, default_value_t = 0)]
    pub limit: u32,

    /// Number of concurrent vision-LLM workers. Each worker holds one
    /// asset; raise carefully — the upstream gateway may rate-limit.
    #[arg(long, default_value_t = 4)]
    pub parallel: u32,

    /// Print the decision for each asset but do NOT call the LLM and do
    /// NOT PUT anything back to Immich.
    #[arg(long)]
    pub dry_run: bool,

    /// Ignore the "sha and version match → skip" rule. Useful when
    /// re-prompting the same library without bumping CURRENT_VERSION.
    #[arg(long)]
    pub force: bool,
}

#[derive(Copy, Clone, Debug, ValueEnum)]
pub enum AssetTypeArg {
    Image,
    Video,
    Audio,
    Other,
}

impl AssetTypeArg {
    fn as_api_str(self) -> &'static str {
        match self {
            AssetTypeArg::Image => "IMAGE",
            AssetTypeArg::Video => "VIDEO",
            AssetTypeArg::Audio => "AUDIO",
            AssetTypeArg::Other => "OTHER",
        }
    }
}

// ---- footer marker -------------------------------------------------------

const FOOTER_PREFIX: &str = "—generated by immich-cli/v";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Footer {
    pub version: u32,
    pub sha_prefix: String,
}

/// Strip a trailing footer if one is present, returning the body and the
/// parsed footer separately. If no footer, returns the input unchanged
/// and `None`.
pub fn split_footer(description: &str) -> (&str, Option<Footer>) {
    // Footer is always on the last non-blank line.
    let trimmed = description.trim_end();
    let last_line_start = trimmed.rfind('\n').map(|i| i + 1).unwrap_or(0);
    let last_line = &trimmed[last_line_start..];
    let Some(rest) = last_line.strip_prefix(FOOTER_PREFIX) else {
        return (description, None);
    };
    let (version_str, after_version) = match rest.split_once(' ') {
        Some(p) => p,
        None => return (description, None),
    };
    let Ok(version) = version_str.parse::<u32>() else {
        return (description, None);
    };
    let sha_prefix = match after_version.strip_prefix("sha=") {
        Some(s) => s.to_string(),
        None => return (description, None),
    };

    // Body = everything before the footer line, trimmed of trailing
    // whitespace (we add `\n\n` ourselves on re-write).
    let body = trimmed[..last_line_start].trim_end();
    (
        body,
        Some(Footer {
            version,
            sha_prefix,
        }),
    )
}

/// Build the new description: body + blank line + footer.
pub fn assemble_with_footer(body: &str, checksum: &str) -> String {
    let body = body.trim_end();
    let prefix = sha_prefix(checksum);
    format!("{body}\n\n{FOOTER_PREFIX}{CURRENT_VERSION} sha={prefix}")
}

pub fn sha_prefix(checksum: &str) -> String {
    checksum.chars().take(SHA_PREFIX_LEN).collect()
}

/// What we want to do with one asset, given its current description and
/// the runtime flags. Pure function so the decision tree is unit-testable
/// independent of LLM / HTTP.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Decision {
    /// Description is empty or we control the footer — go (re-)caption.
    /// The reason is informational; tests assert on it.
    Caption(CaptionReason),
    /// Already up to date, leave alone.
    Skip(SkipReason),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CaptionReason {
    EmptyDescription,
    ChecksumChanged,
    VersionUpgraded,
    Forced,
    OverwroteForeign,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SkipReason {
    UpToDate,
}

pub fn decide(description: Option<&str>, checksum: &str, force: bool) -> Decision {
    let desc = description.unwrap_or("").trim();
    if desc.is_empty() {
        return Decision::Caption(CaptionReason::EmptyDescription);
    }
    let (_, footer) = split_footer(desc);
    match footer {
        Some(f) => {
            // We own this description (we wrote it before).
            if force {
                Decision::Caption(CaptionReason::Forced)
            } else if f.sha_prefix != sha_prefix(checksum) {
                Decision::Caption(CaptionReason::ChecksumChanged)
            } else if f.version < CURRENT_VERSION {
                Decision::Caption(CaptionReason::VersionUpgraded)
            } else {
                Decision::Skip(SkipReason::UpToDate)
            }
        }
        // No footer = camera EXIF / app noise; always overwrite.
        None => Decision::Caption(CaptionReason::OverwroteForeign),
    }
}

// ---- prompt --------------------------------------------------------------

const CAPTION_SYSTEM_PROMPT: &str = "你是一位帮助用户为照片生成中文描述的助手。\
你的输出会作为搜索/检索系统的输入，因此需要尽可能全面、客观、可搜索。";

const CAPTION_USER_PROMPT: &str =
    "请尽可能详尽地分析这张图片，为一个纯文本的下游搜索/检索模型生成中文描述。\n\n\
请描述以下方面（按图片实际内容取舍，没有的可不写）：\n\
- 主体物体、人物（数量、姿态、衣着、动作、表情等可观察到的细节）\n\
- 场景、地理环境、室内或室外\n\
- 光线、色彩、氛围、季节/时间感\n\
- 布局与构图、前景与背景的关系\n\
- 任何能帮助识别具体地点、品牌、产品或场景的独特视觉线索\n\n\
规则：\n\
- 严格区分\"观察到的事实\"和\"不确定的推断\"，不确定的部分请用\"看起来像\"、\"推测为\"等词标注\n\
- 不要做超出图像本身的猜测\n\
- 全文使用中文\n\
- 总长度不超过 3000 字";

// ---- single-asset caption pipeline ---------------------------------------

/// Produce a fresh description for one asset by fetching its thumbnail
/// and asking the vision model. The footer is appended here.
pub fn caption_one<C, V>(client: &C, llm: &V, asset_id: &str, checksum: &str) -> Result<String>
where
    C: CaptionBackend,
    V: CaptionLlm,
{
    let bytes = client.thumbnail(asset_id)?;
    let body = llm.caption(
        CAPTION_SYSTEM_PROMPT,
        CAPTION_USER_PROMPT,
        &bytes,
        "image/jpeg",
        MAX_COMPLETION_TOKENS,
    )?;
    Ok(assemble_with_footer(body.trim(), checksum))
}

// ---- candidate enumeration -----------------------------------------------

fn enumerate_candidates<S: SearchBackend>(
    search: &S,
    args: &UpdateDescriptionsArgs,
) -> Result<Vec<Asset>> {
    let mut all = Vec::new();
    let mut page = 1u32;
    loop {
        let req = SearchRequest {
            taken_after: args.taken_after.clone(),
            taken_before: args.taken_before.clone(),
            city: args.city.clone(),
            state: args.state.clone(),
            country: args.country.clone(),
            asset_type: args.r#type.map(|t| t.as_api_str().to_string()),
            size: Some(1000),
            page: Some(page),
            with_exif: Some(true),
            ..Default::default()
        };
        let resp = search.search(&req)?;
        if resp.assets.items.is_empty() {
            break;
        }
        let has_more = resp.assets.next_page.as_ref().is_some_and(|v| !v.is_null());
        all.extend(resp.assets.items);
        if !has_more {
            break;
        }
        page += 1;
    }
    Ok(all)
}

fn resolve_single<S: SearchBackend>(
    cfg: &Config,
    search: &S,
    path: &std::path::Path,
) -> Result<Asset> {
    let local_abs = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .context("cannot resolve cwd")?
            .join(path)
    };
    let server_path = path_map::reverse_translate(&local_abs.to_string_lossy(), &cfg.path_map)
        .ok_or_else(|| {
            anyhow!(
                "no path mapping matches {} — add a [[path_map]] entry",
                local_abs.display()
            )
        })?;
    let filename = std::path::Path::new(&server_path)
        .file_name()
        .map(|s| s.to_string_lossy().into_owned())
        .ok_or_else(|| anyhow!("could not extract filename from `{server_path}`"))?;
    let req = SearchRequest {
        original_file_name: Some(filename.clone()),
        size: Some(250),
        with_exif: Some(true),
        ..Default::default()
    };
    let resp = search.search(&req)?;
    let mut matches: Vec<Asset> = resp
        .assets
        .items
        .into_iter()
        .filter(|a| a.original_path == server_path)
        .collect();
    match matches.len() {
        0 => bail!(
            "no Immich asset has originalPath `{server_path}` \
             (filename `{filename}` was not found)"
        ),
        1 => Ok(matches.pop().unwrap()),
        n => bail!(
            "{n} Immich assets share originalPath `{server_path}` \
             — should never happen"
        ),
    }
}

// ---- orchestration -------------------------------------------------------

pub fn run(cfg: &Config, args: UpdateDescriptionsArgs) -> Result<()> {
    let llm_cfg = cfg.llm.as_ref().ok_or_else(|| {
        anyhow!(
            "update-descriptions requires an [llm] section in config.toml \
             with vision_model set"
        )
    })?;
    if llm_cfg.vision_model.as_deref().unwrap_or("").is_empty() {
        bail!(
            "update-descriptions requires config.llm.vision_model — set it to a \
             vision-capable model (e.g. \"mimo-v2.5\")"
        );
    }
    let client = ImmichClient::new(cfg)?;
    let llm = OpenAiClient::new(llm_cfg)?;
    run_with(cfg, &client, &client, &llm, args, &mut std::io::stderr())
}

/// Test/library entry point: decouples the runtime from concrete client
/// and LLM types. Logging goes to `log` so tests can capture it.
pub fn run_with<S, C, V, W>(
    cfg: &Config,
    search: &S,
    caption_be: &C,
    llm: &V,
    args: UpdateDescriptionsArgs,
    log: &mut W,
) -> Result<()>
where
    S: SearchBackend + Sync,
    C: CaptionBackend + Sync,
    V: CaptionLlm + Sync,
    W: std::io::Write + Send,
{
    if args.parallel == 0 {
        bail!("--parallel must be > 0");
    }

    let candidates = if let Some(p) = &args.path {
        vec![resolve_single(cfg, search, p)?]
    } else {
        writeln!(log, "scanning library ...").ok();
        enumerate_candidates(search, &args)?
    };
    writeln!(log, "{} asset(s) match filter", candidates.len()).ok();

    // Decide per asset BEFORE we burn LLM tokens. This lets dry-run be
    // a true preview, and lets --limit cap captions (not enumeration).
    let planned: Vec<(Asset, Decision)> = candidates
        .into_iter()
        .map(|a| {
            let desc = a.exif_info.as_ref().and_then(|e| e.description.as_deref());
            let dec = decide(desc, &a.checksum, args.force);
            (a, dec)
        })
        .collect();

    let work: Vec<&(Asset, Decision)> = planned
        .iter()
        .filter(|(_, d)| matches!(d, Decision::Caption(_)))
        .take(if args.limit == 0 {
            usize::MAX
        } else {
            args.limit as usize
        })
        .collect();

    let skipped_up_to_date = planned
        .iter()
        .filter(|(_, d)| matches!(d, Decision::Skip(SkipReason::UpToDate)))
        .count();
    writeln!(
        log,
        "{} up to date, {} to caption",
        skipped_up_to_date,
        work.len()
    )
    .ok();

    if args.dry_run {
        for (asset, dec) in &work {
            if let Decision::Caption(r) = dec {
                writeln!(
                    log,
                    "DRY-RUN caption ({:?}): {} {}",
                    r, asset.id, asset.original_path
                )
                .ok();
            }
        }
        return Ok(());
    }

    if work.is_empty() {
        return Ok(());
    }

    process_in_parallel(caption_be, llm, &work, args.parallel as usize, log)
}

/// Run vision + PUT for each item in parallel. Errors on individual
/// assets are logged but do not abort the whole run.
fn process_in_parallel<C, V, W>(
    caption_be: &C,
    llm: &V,
    work: &[&(Asset, Decision)],
    parallel: usize,
    log: &mut W,
) -> Result<()>
where
    C: CaptionBackend + Sync,
    V: CaptionLlm + Sync,
    W: std::io::Write + Send,
{
    let next = AtomicUsize::new(0);
    let succeeded = AtomicUsize::new(0);
    let failed = AtomicUsize::new(0);
    let log_lock = Mutex::new(log);

    std::thread::scope(|scope| {
        for _ in 0..parallel.min(work.len()) {
            scope.spawn(|| loop {
                let i = next.fetch_add(1, Ordering::SeqCst);
                if i >= work.len() {
                    break;
                }
                let (asset, decision) = work[i];
                let reason = match decision {
                    Decision::Caption(r) => *r,
                    Decision::Skip(_) => unreachable!("filtered above"),
                };
                let res = caption_one(caption_be, llm, &asset.id, &asset.checksum)
                    .and_then(|new_desc| caption_be.update_description(&asset.id, &new_desc));
                let mut log = log_lock.lock().unwrap();
                match res {
                    Ok(()) => {
                        succeeded.fetch_add(1, Ordering::SeqCst);
                        writeln!(
                            *log,
                            "ok ({:?}) [{}/{}]: {} {}",
                            reason,
                            i + 1,
                            work.len(),
                            asset.id,
                            asset.original_path
                        )
                        .ok();
                    }
                    Err(e) => {
                        failed.fetch_add(1, Ordering::SeqCst);
                        writeln!(
                            *log,
                            "FAIL [{}/{}]: {} {} — {e:#}",
                            i + 1,
                            work.len(),
                            asset.id,
                            asset.original_path
                        )
                        .ok();
                    }
                }
            });
        }
    });

    let log = log_lock.into_inner().unwrap();
    writeln!(
        log,
        "done: {} captioned, {} failed",
        succeeded.into_inner(),
        failed.into_inner()
    )
    .ok();
    Ok(())
}

// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::PathMapEntry;
    use crate::models::{AssetsBucket, ExifInfo, SearchResponse};
    use std::cell::RefCell;
    use std::sync::Mutex;

    fn asset_with(id: &str, path: &str, checksum: &str, description: Option<&str>) -> Asset {
        Asset {
            id: id.into(),
            original_path: path.into(),
            original_file_name: path.rsplit('/').next().unwrap_or(path).into(),
            asset_type: "IMAGE".into(),
            file_created_at: None,
            local_date_time: None,
            checksum: checksum.into(),
            exif_info: Some(ExifInfo {
                city: None,
                state: None,
                country: None,
                latitude: None,
                longitude: None,
                description: description.map(String::from),
            }),
        }
    }

    fn cfg() -> Config {
        Config {
            server_url: "http://x".into(),
            api_key: "k".into(),
            path_map: vec![PathMapEntry {
                server: "/mnt/qnap".into(),
                local: "/home/u/Photos".into(),
            }],
            timeout_secs: 60,
            llm: None,
        }
    }

    // ---- footer parsing ----

    #[test]
    fn split_footer_extracts_version_and_sha() {
        let s = "正文内容\n\n—generated by immich-cli/v1 sha=abc123def456";
        let (body, footer) = split_footer(s);
        assert_eq!(body, "正文内容");
        assert_eq!(
            footer,
            Some(Footer {
                version: 1,
                sha_prefix: "abc123def456".into()
            })
        );
    }

    #[test]
    fn split_footer_handles_v2_and_longer_sha() {
        let s = "x\n\n—generated by immich-cli/v42 sha=ZZZZZZZZZZZZZ";
        let (_, footer) = split_footer(s);
        let f = footer.unwrap();
        assert_eq!(f.version, 42);
        assert_eq!(f.sha_prefix, "ZZZZZZZZZZZZZ");
    }

    #[test]
    fn split_footer_returns_none_when_absent() {
        let s = "a human-written caption with no marker";
        let (body, footer) = split_footer(s);
        assert_eq!(body, s);
        assert!(footer.is_none());
    }

    #[test]
    fn split_footer_returns_none_on_malformed() {
        for s in [
            "x\n—generated by immich-cli/vONE sha=abc",
            "x\n—generated by immich-cli/v1",
            "x\n—generated by immich-cli/v1 sh=abc",
        ] {
            let (body, footer) = split_footer(s);
            assert_eq!(body, s, "input: {s}");
            assert!(footer.is_none(), "input: {s}");
        }
    }

    #[test]
    fn assemble_round_trips() {
        let body = "这是描述正文";
        let combined = assemble_with_footer(body, "kL2A3+Icry1aqhydhTrFlw2LZ/U=");
        let (got_body, footer) = split_footer(&combined);
        assert_eq!(got_body, body);
        let f = footer.unwrap();
        assert_eq!(f.version, CURRENT_VERSION);
        assert_eq!(f.sha_prefix, "kL2A3+Icry1a");
    }

    // ---- decide() ----

    #[test]
    fn decide_caption_when_description_is_none_or_empty() {
        let d1 = decide(None, "abc", false);
        let d2 = decide(Some(""), "abc", false);
        let d3 = decide(Some("   "), "abc", false);
        for d in [d1, d2, d3] {
            assert_eq!(d, Decision::Caption(CaptionReason::EmptyDescription));
        }
    }

    #[test]
    fn decide_skip_when_up_to_date() {
        let footer = assemble_with_footer("正文", "abcdef123456xyz");
        let d = decide(Some(&footer), "abcdef123456xyz", false);
        assert_eq!(d, Decision::Skip(SkipReason::UpToDate));
    }

    #[test]
    fn decide_recaption_when_sha_changes() {
        let footer = assemble_with_footer("正文", "OLD_CHECKSUM_____");
        let d = decide(Some(&footer), "NEW_CHECKSUM_____", false);
        assert_eq!(d, Decision::Caption(CaptionReason::ChecksumChanged));
    }

    #[test]
    fn decide_recaption_when_version_older() {
        let s = format!(
            "正文\n\n—generated by immich-cli/v0 sha={}",
            sha_prefix("abc")
        );
        let d = decide(Some(&s), "abc", false);
        assert_eq!(d, Decision::Caption(CaptionReason::VersionUpgraded));
    }

    #[test]
    fn decide_caption_when_foreign_description() {
        // No footer = camera noise; always overwrite.
        for s in ["cof", "PixCake", "Exif_JPEG_420", "a human-written caption"] {
            let d = decide(Some(s), "abc", false);
            assert_eq!(
                d,
                Decision::Caption(CaptionReason::OverwroteForeign),
                "input: {s}"
            );
        }
    }

    #[test]
    fn decide_force_overrides_uptodate() {
        let footer = assemble_with_footer("正文", "abcdef123456xyz");
        let d = decide(Some(&footer), "abcdef123456xyz", false);
        assert_eq!(d, Decision::Skip(SkipReason::UpToDate));
        let forced = decide(Some(&footer), "abcdef123456xyz", true);
        assert_eq!(forced, Decision::Caption(CaptionReason::Forced));
    }

    // ---- end-to-end via run_with ----

    struct FakeSearch {
        responses: RefCell<Vec<SearchResponse>>,
        calls: RefCell<Vec<SearchRequest>>,
    }
    impl FakeSearch {
        fn new(responses: Vec<SearchResponse>) -> Self {
            Self {
                responses: RefCell::new(responses),
                calls: RefCell::new(vec![]),
            }
        }
    }
    impl SearchBackend for FakeSearch {
        fn search(&self, req: &SearchRequest) -> Result<SearchResponse> {
            self.calls.borrow_mut().push(req.clone());
            Ok(self.responses.borrow_mut().remove(0))
        }
    }
    // SearchBackend isn't naturally Sync (RefCell); wrap.
    unsafe impl Sync for FakeSearch {}

    struct FakeCaption {
        thumbnails: Mutex<std::collections::HashMap<String, Vec<u8>>>,
        updates: Mutex<Vec<(String, String)>>,
    }
    impl FakeCaption {
        fn new() -> Self {
            Self {
                thumbnails: Mutex::new(std::collections::HashMap::new()),
                updates: Mutex::new(vec![]),
            }
        }
    }
    impl CaptionBackend for FakeCaption {
        fn thumbnail(&self, id: &str) -> Result<Vec<u8>> {
            Ok(self
                .thumbnails
                .lock()
                .unwrap()
                .get(id)
                .cloned()
                .unwrap_or_else(|| vec![0u8; 32]))
        }
        fn update_description(&self, id: &str, description: &str) -> Result<()> {
            self.updates
                .lock()
                .unwrap()
                .push((id.into(), description.into()));
            Ok(())
        }
    }

    struct FakeVision {
        reply: String,
    }
    impl CaptionLlm for FakeVision {
        fn caption(
            &self,
            _system_prompt: &str,
            _user_prompt: &str,
            _image_bytes: &[u8],
            _mime: &str,
            _max_tokens: u32,
        ) -> Result<String> {
            Ok(self.reply.clone())
        }
    }

    fn bucket(items: Vec<Asset>) -> SearchResponse {
        SearchResponse {
            assets: AssetsBucket {
                total: items.len() as u32,
                count: items.len() as u32,
                items,
                next_page: None,
            },
        }
    }

    fn args() -> UpdateDescriptionsArgs {
        UpdateDescriptionsArgs {
            path: None,
            taken_after: None,
            taken_before: None,
            city: None,
            state: None,
            country: None,
            r#type: None,
            limit: 0,
            parallel: 2,
            dry_run: false,
            force: false,
        }
    }

    #[test]
    fn run_with_captions_empty_and_foreign_descriptions() {
        let search = FakeSearch::new(vec![bucket(vec![
            asset_with("a", "/mnt/qnap/a.jpg", "cs-a-xxxxx", None),
            asset_with("b", "/mnt/qnap/b.jpg", "cs-b-xxxxx", Some("cof")),
            asset_with(
                "c",
                "/mnt/qnap/c.jpg",
                "cs-c-xxxxx",
                Some(&assemble_with_footer("旧描述", "cs-c-xxxxx")),
            ),
        ])]);
        let caption = FakeCaption::new();
        let vision = FakeVision {
            reply: "新描述".into(),
        };
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, args(), &mut log).unwrap();

        let mut updates = caption.updates.lock().unwrap().clone();
        updates.sort_by(|a, b| a.0.cmp(&b.0));
        // 'a' (empty) and 'b' (foreign noise) both captioned; 'c' up-to-date.
        assert_eq!(updates.len(), 2, "got: {updates:?}");
        assert_eq!(updates[0].0, "a");
        assert_eq!(updates[1].0, "b");
        for u in &updates {
            assert!(u.1.contains("新描述"));
            assert!(u.1.contains("—generated by immich-cli/v"));
        }

        let log_s = String::from_utf8(log).unwrap();
        assert!(log_s.contains("up to date"), "{log_s}");
    }

    #[test]
    fn run_with_dry_run_does_not_call_llm_or_update() {
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "a",
            "/mnt/qnap/a.jpg",
            "cs-a-xxxxx",
            None,
        )])]);
        let caption = FakeCaption::new();
        let vision = FakeVision { reply: "X".into() };
        let mut a = args();
        a.dry_run = true;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        assert!(caption.updates.lock().unwrap().is_empty());
        let log_s = String::from_utf8(log).unwrap();
        assert!(log_s.contains("DRY-RUN"));
    }

    #[test]
    fn run_with_force_replaces_up_to_date() {
        let existing = assemble_with_footer("旧的", "cs-a");
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "a",
            "/mnt/qnap/a.jpg",
            "cs-a",
            Some(&existing),
        )])]);
        let caption = FakeCaption::new();
        let vision = FakeVision {
            reply: "新的".into(),
        };
        let mut a = args();
        a.force = true;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        let updates = caption.updates.lock().unwrap();
        assert_eq!(updates.len(), 1);
        assert!(updates[0].1.contains("新的"));
    }

    #[test]
    fn run_with_limit_caps_captions_not_enumeration() {
        // 3 empty assets; --limit 2 means only the first two get LLM'd
        let search = FakeSearch::new(vec![bucket(vec![
            asset_with("a", "/mnt/qnap/a.jpg", "cs-a", None),
            asset_with("b", "/mnt/qnap/b.jpg", "cs-b", None),
            asset_with("c", "/mnt/qnap/c.jpg", "cs-c", None),
        ])]);
        let caption = FakeCaption::new();
        let vision = FakeVision { reply: "x".into() };
        let mut a = args();
        a.limit = 2;
        let mut log = Vec::new();
        run_with(&cfg(), &search, &caption, &vision, a, &mut log).unwrap();
        assert_eq!(caption.updates.lock().unwrap().len(), 2);
    }

    #[test]
    fn caption_one_appends_footer() {
        struct CB;
        impl CaptionBackend for CB {
            fn thumbnail(&self, _: &str) -> Result<Vec<u8>> {
                Ok(vec![0u8; 8])
            }
            fn update_description(&self, _: &str, _: &str) -> Result<()> {
                Ok(())
            }
        }
        let llm = FakeVision {
            reply: "正文".into(),
        };
        let got = caption_one(&CB, &llm, "asset-id", "checksum-xyz-aaa").unwrap();
        let (body, footer) = split_footer(&got);
        assert_eq!(body, "正文");
        let f = footer.unwrap();
        assert_eq!(f.version, CURRENT_VERSION);
        assert_eq!(f.sha_prefix, "checksum-xyz");
    }

    // ---- single-asset path resolution ----

    #[test]
    fn resolve_single_uses_reverse_path_mapping() {
        let search = FakeSearch::new(vec![bucket(vec![asset_with(
            "the-id",
            "/mnt/qnap/PYL/x.jpg",
            "cs",
            None,
        )])]);
        let got = resolve_single(
            &cfg(),
            &search,
            std::path::Path::new("/home/u/Photos/PYL/x.jpg"),
        )
        .unwrap();
        assert_eq!(got.id, "the-id");
    }

    #[test]
    fn resolve_single_errors_when_no_mapping() {
        let search = FakeSearch::new(vec![]);
        let err = resolve_single(&cfg(), &search, std::path::Path::new("/elsewhere/x.jpg"))
            .unwrap_err()
            .to_string();
        assert!(err.contains("no path mapping"));
    }
}
